apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-python
  namespace: e2e-demo-pcjn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/codewindbtle/test-images@sha256:142be1b7799ea9ac8f8f5ec05e6416e33d9ce81087271e2bf4719f4114d7ec81
        name: container-image
        resources: {}
status: {}
